=== Namratha490/WebTech/E-learningXML/home.dtd
<!ELEMENT home (heading,navigation, dropdown, button, footer)>
<!ELEMENT heading (#PCDATA)>
<!ELEMENT navigation (category*)>
<!ELEMENT category (#PCDATA)>
<!ELEMENT dropdown (option*)>
<!ELEMENT option (#PCDATA)>
<!ELEMENT button (#PCDATA)>
<!ELEMENT footer (icon*)>
<!ELEMENT icon (#PCDATA)>

<!ATTLIST category link CDATA #REQUIRED>
<!ATTLIST button link CDATA #REQUIRED>
<!ATTLIST icon link CDATA #REQUIRED>

=== Namratha490/WebTech/E-learningXML/home.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="home.xsl"?>
<!DOCTYPE home SYSTEM "home.dtd">

<home>
 <heading> Learn a Language</heading>
<navigation>
     <category link="path of the page"> Log in ></category>
	 <category link="path of the page"> Start Learning ></category>
	 
</navigation>


<dropdown>
    <option> Hindi </option>
    <option>French</option>
    <option> Spanish</option>
</dropdown>
<button link="login.xml" > Get Started </button>

<footer>
<icon  link="facebook.com" > facebook </icon>
<icon  link="instagram.com"> instagram </icon>
<icon  link="twitter.com"> twitter</icon>

 </footer>
 
</home>
